# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ff6d03aa0b89e4a67fe9615ce2920c142eab904c4d27ce507aaddde82b18a475b3a6e3becb5706a2282c36b6f32b8554e712b26a9f8953220536c3d0bd47eec0

test:
  secret_key_base: b229725220d152abd5d48722c9c2c177b10e1bda928f1bd498888773c1f4e30ff0abe2fab4067f89c8c454e24e026662cb301109f9fddf33139fb848bc57c47e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
